#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
PID_FILE=/usr/local/var/run/radiusd/radiusd.pid

function start_app {
/usr/local/sbin/radiusd 2>&1 &
}

function stop_app {
PID=`cat $PID_FILE`
kill -- -$(ps -o pgid= $PID | grep -o [0-9]*)
}

function status_app {
if [ -f "$PID_FILE" ]; then
     PID=`cat $PID_FILE`
     if ps --pid $PID 2>&1 1>/dev/null; then
       echo "RADIUS Server is already running at ${PID}"
     else
       echo "$PID_FILE found, but $PID is not running"
     fi
     unset PID
   else
     echo "RADIUS Server is stopped"
fi
}

case $1 in
start)
start_app ;;
stop)
stop_app ;;
restart)
stop_app
start_app ;;
status)
status_app
;;
*)

echo "usage: radiusd {start|stop|restart|status}" ;;
esac
exit 0
