#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
BIND_IP=127.0.0.1
BIND_PORT=8888
INTERIM_INTERVAL=8000
ALLOWED_HOST=0.0.0.0
PID_FILE=/var/run/soapradius.pid
LOG_FILE=/var/log/soapradius.log


function start_app {
/bin/soapradius $BIND_PORT $BIND_IP $INTERIM_INTERVAL $ALLOWED_HOST >> $LOG_FILE 2>&1 &
echo -n $! > "$PID_FILE"
}

function stop_app {
PID=`cat $PID_FILE`
kill -- -$(ps -o pgid= $PID | grep -o [0-9]*)
rm -rf $PID_FILE
}

function status_app {
if [ -f "$PID_FILE" ]; then
     PID=`cat $PID_FILE`
     if ps --pid $PID 2>&1 1>/dev/null; then
       echo "Soapradius is already running at ${PID}"
     else
       echo "$PID_FILE found, but $PID is not running"
     fi
     unset PID
   else
     echo "Soapradius is stopped"
fi
}

case $1 in
start)
start_app ;;
stop)
stop_app ;;
restart)
stop_app
start_app ;;
status)
status_app
;;
*)

echo "usage: soapradius {start|stop|restart|status}" ;;
esac
exit 0
